@startuml

enum UserRole {
    TEACHER
    STUDENT
    ADMIN
}
enum LearningActivityType {
    MULTIPLECHOICE
    FILLINTHEBLANK
    INSTRUCTION
    QUIZ
}

enum FriendRequestStatus {
    ACCEPTED
    DECLINED
    PENDING
    CANCELLED
    BLOCKED
}

enum RewardType {
    DIPLOMA
    BADGE
}

enum ProgressStatus {
    COMPLETED
    INPROGRESS
    NOTSTARTED
}

enum ProgressType {
    MODULE
    ACTIVITY
}

class Administration {
    + Administration()
    + AddUser(user: User)
    + UpdateUser(user: User)
    + AddLearningModule(module: LearningModule)
    + RemoveLearningModule(module: LearningModule)
}

class LearningModule {
    -id: Int
    -name: String
    -description: String
    +LearningModule(name: String, description: String)
    +AddLearningActivity(activity: LearningActivity)
    +RemoveLearningActivity(activity: LearningActivity)
    +ShowLearningActivities(): List<LearningActivity>
}


class LearningActivity {
    -id: Int
    -name: String
    -description: String
    -type: LearningActivityType
    +LearningActivity(name: String, description: String, type: LearningActivityType)
    +UpdateActivity(name: String, description: String, type: LearningActivityType)
}


class User {
    -id: Int
    -firstName: String
    -middleName: String
    -lastName: String
    -dateOfBirth: Date
    -email: String
    -password: String
    -role: UserRole
    +User(firstName: String, middleName: String, lastName: String, dateOfBirth: Date, email: String, password: String, role: UserRole)
    +UpdateProfile(firstName: String, middleName: String, lastName: String, email: String, password: String)
    +SetRole(role: UserRole)
}

class Reward {
    -name: String
    -type: RewardType
    -description: String
    -date: Date
    +Reward(name: String, type: RewardType, description: String, date: Date)
    +ShowDetails(): String
}

class FriendRequest {
    - id: Int
    - sender: User
    - recipient: User
    - status: FriendRequestStatus
    +FriendRequest(sender: User, recipient: User)
    +UpdateStatus(status: FriendRequestStatus)
}

class Progress {
    -id: Int
    -type: ProgressType
    -status: ProgressStatus
    -progressDetails: String
    +Progress(type: ProgressType, status: ProgressStatus, progressDetails: String)
    +ShowDetails(): String
    +UpdateProgress(details: String)
}

Administration "1" -right-> "n" User
Administration "1" -down-> "n" LearningModule

User -up-> "n" Reward
User -right-> "n" Progress

User "1" -up-> "n" FriendRequest : sent
User "1" <-up- "n" FriendRequest : received

Progress "1" -down-> "1" LearningActivity

LearningModule "1" --> "n" LearningActivity


@enduml