@startuml
left to right direction
actor Admin
actor Leerling
actor Medeleerling
actor Leerkracht

rectangle "LingoPartner App" {
  usecase "Gebruiker Aanmaken" as UC1
  usecase "Profiel Aanpassen" as UC2
  usecase "Collectie aanmaken" as UC3
  usecase "Leeractiviteit Aanmaken" as UC4
  usecase "Voortgang bekijken" as UC5
  usecase "Leeractiviteit Uitvoeren" as UC6
  usecase "Reeds Gestarte Collectie Hervatten" as UC7
  usecase "Voortgang Delen met Medeleerlingen" as UC8

  Admin --> UC1
  Leerling --> UC2
  Leerling --> UC5
  Leerling --> UC6
  Leerling --> UC7
  Leerling --> UC8
  Leerkracht --> UC3
  Leerkracht --> UC4
  Leerkracht --> UC5
  Medeleerling --> UC5
  Medeleerling <-- UC8
}
@enduml