@startuml
' Entiteiten (Zelfstandige Naamwoorden)
entity Pretpark
entity Attractie
entity Ticketverkoop
entity Bezoeker
entity Kaartje
entity Systeem
entity Data
entity Overzicht
' entity Medewerkerspas
entity Klant
entity Wachtrij
entity Medewerker
' entity Ziekte
' entity Eetvoorkeur
' Relaties
Pretpark "1" -- "*" Bezoeker : >
Pretpark "1" -- "1" Ticketverkoop : >
Pretpark "1" -- "*" Attractie : >
Pretpark "1" -- "*" Medewerker : >
' Medewerker "1" -- "1" Medewerkerspas : >
' Bezoeker "1" -- "0..*" Ziekte : >
' Bezoeker "1" -- "*" Eetvoorkeur : >
Bezoeker "1" -- "1" Kaartje : >
Ticketverkoop "1" -- "*" Klant : >
Klant "1" -- "*" Kaartje : >
Attractie "1" -- "1" Wachtrij : >
Wachtrij "1" -- "*" Bezoeker : >
Systeem "1" -- "*" Data : >
Systeem "1" -- "*" Overzicht : >
@enduml