@startuml

' Klassen
class Pretpark {
    - naam: String

    + Pretpark(naam: String): ctor
}

class Klant {
    - naam: String
    - leeftijd: date

    + Klant(naam: String, leeftijd: int): ctor
}

' class Bezoeker extends Klant{
class Bezoeker {
    - kaartje: Kaartje
    - eetvoorkeur: String

    + Bezoeker(kaartje: Kaartje, eetvoorkeur: String, leeftijd: int): ctor
    + BerekenGezondheidsrisico(): boolean
}

class Kaartje {
    - datum: Date
    - prijs: double
    - klant: Klant

    + Kaartje(datum: Date, prijs: double, klant: Klant): ctor
}

class Attractie {
    - naam: String
    - minLeeftijd: int
    - minLengte: double
    - maxLengte: double
    - toegankelijkVoorHartVaatziekten: boolean

    + Attractie(naam: String, minLeeftijd: int, minLengte: double, maxLengte: double, toegankelijkVoorHartVaatziekten: boolean, wachtrij: Wachtrij): ctor
    + ControleerToegankelijkheid(Bezoeker): boolean
}

class Medewerker {
    - naam: String
    - medewerkersnummer: String

    + Medewerker(naam: String, medewerkersnummer: String)
    + ScanKaartje(Kaartje): boolean
}

class Ticketverkoop {
    - verkochteTickets: int
    - totaleOpbrengst: double

    + Ticketverkoop(): ctor
    + RegistreerKlant(klant: Klant): void
    + VerkoopKaartje(klant: Klant, bezoeker: Bezoeker): Kaartje
}

class Wachtrij {
    - maxLengte: int

    + VoegBezoekerAanWachtrijToe(bezoeker: Bezoeker): boolean
    + CheckGezondheidsRisico(bezoeker: Bezoeker): boolean
    + ValideerToegang(bezoeker: Bezoeker): boolean
    + updateWachtrijlengte(): void
}

' Relaties
Pretpark "1" -- "1..*" Medewerker : heeft >
Pretpark "1" -- "1" Ticketverkoop : heeft > 
Ticketverkoop "1" -- "*" Klant : heeft >
Ticketverkoop "1" -- "*" Kaartje : heeft >
Klant "*" -- "*" Kaartje : heeft >
Bezoeker "1" -- "1" Kaartje : heeft >
Kaartje "1" -- "1" Klant : heeft >
Wachtrij "1" -- "*" Bezoeker : heeft >
Attractie "1" -- "1" Wachtrij : heeft >

@enduml
