@startuml
left to right direction

' Actoren
actor Klant
actor Medewerker
actor Directeur
actor Systeem

' Use cases
rectangle PretparkSysteem {
  (Koop Kaartje) as KoopKaartje
  (Bekijk Beschikbaarheid Kaartjes) as BekijkBeschikbaarheid
  (Download en Print Kaartje) as DownloadPrint
  (Inchecken bij Pretpark) as IncheckenPretpark
  (Scan Kaartje bij Attractie) as ScanKaartje
  (Bekijk Wachtrij Informatie) as BekijkWachtrij
  (Bekijk Verkoop Tickets) as BekijkVerkoop
  (Voer Gegevens In) as VoerGegevensIn
  (Bepaal Toegankelijkheid Attractie) as BepaalToegankelijkheid
  (Geef Eetvoorkeur op) as GeefEetvoorkeurOp
}

' Relaties
Klant --> KoopKaartje
Klant --> BekijkBeschikbaarheid
Klant --> DownloadPrint
Klant --> IncheckenPretpark
Klant --> ScanKaartje
Klant --> VoerGegevensIn
Klant --> GeefEetvoorkeurOp
IncheckenPretpark --> Medewerker
BekijkWachtrij --> Medewerker
Directeur --> BekijkVerkoop
Systeem --> BepaalToegankelijkheid

@enduml