@startuml

rectangle Leerling
rectangle Leerkracht
rectangle Vriend
rectangle EducatieveInhoud as "Educatieve Inhoud"
' rectangle Collectie
' rectangle Hoofdstukken
rectangle Leeractiviteit
rectangle Voortgang
rectangle Beloning
' rectangle Diploma
' rectangle Badge
' rectangle SocialeInteractie as "Vriendenlijst"
' rectangle LeerlingDashboard as "Leerling Dashboard"

Leerkracht "1" -down-> "1..n" EducatieveInhoud : levert
' EducatieveInhoud -down-> Collectie : bestaat uit
' Collectie -right-> Hoofdstukken : omvat
' Hoofdstukken -down-> Leeractiviteit : bevat
EducatieveInhoud "1" -down-> "1..n" Leeractiviteit : bevat

Leerling "1" -left-> "1..n" Leeractiviteit : "neemt deel aan\n/ voert uit"
Leerling "1" -right-> "0..n" Vriend  : heeft
' Leerling "1" -down-> "1" LeerlingDashboard : heeft
Leeractiviteit "1" -down-> "1" Voortgang : levert
Voortgang "1" -up-> "1" Leerling : heeft
Leerling "1" -down-> "1..n" Beloning : heeft
Voortgang "1" -right-> "1..n" Beloning : heeft
' Diploma "1" -up-> "n" Voortgang : heeft
' Badge "1" -up-> "1" Voortgang : heeft
' Beloning "1..n" -up-> "1" Diploma : is
' Beloning "1..n" -up-> "1" Badge : is
' Beloning "n" -right-> "1" LeerlingDashboard : toont

@enduml
