services:
  db:
    image: mariadb:latest
    restart: no
    env_file:
      - .env
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d